// This file is generated by scripts/generate-masm.mjs from the MASM contract sources.
// Do not edit it by hand.

export const GUARDED_MULTISIG_ACCOUNT_COMPONENT_MASM = `# The MASM code of the Multi-Signature Authentication component integrated with a state guardian.
#
# See the \`AuthGuardedMultisig\` Rust type's documentation for more details.

use miden::standards::auth::multisig
use miden::standards::auth::guardian

pub use {update_signers_and_threshold} from miden::standards::auth::multisig
pub use {get_threshold_and_num_approvers} from miden::standards::auth::multisig
pub use {set_procedure_threshold} from miden::standards::auth::multisig
pub use {get_signer_at} from miden::standards::auth::multisig
pub use {is_signer} from miden::standards::auth::multisig

pub use {update_guardian_public_key} from miden::standards::auth::guardian

#! Authenticate a transaction with multi-signature support and optional guardian verification.
#!
#! Inputs:
#!   Operand stack: [SALT]
#! Outputs:
#!   Operand stack: []
#!
#! Invocation: call
@auth_script
pub proc auth_tx_guarded_multisig(salt: word)
    exec.multisig::auth_tx
    # => [TX_SUMMARY_COMMITMENT]

    dupw
    # => [TX_SUMMARY_COMMITMENT, TX_SUMMARY_COMMITMENT]
    
    exec.guardian::verify_signature
    # => [TX_SUMMARY_COMMITMENT]

    exec.multisig::record_and_assert_new_tx
    # => []
end
`;
