[package]
name = "miden-rpc-client"
version = "0.1.0"
edition = "2021"

[dependencies]
miden-protocol = { workspace = true }
tonic = { workspace = true, features = ["tls-native-roots", "tls-ring", "transport"] }
tonic-prost = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
hex = { workspace = true }

[build-dependencies]
miden-node-proto-build = { workspace = true }
tonic-prost-build = { workspace = true }
